name: Testes de unidade (xUnit)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    name: Executar testes de unidade
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['9.0.x']
    steps:
      - name: Checkout
        uses: actions/chackout@v4
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./backend

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./backend
